services:

    mysql:
        image: mysql:8.0
        container_name: mysql_container
        restart: always
        environment:
            MYSQL_DATABASE: fraudscope
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

        ports:
            - "3306:3306"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 30s
            timeout: 10s
            retries: 5
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - fraudscope_network

    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: fraudscope:0.0.1
        container_name: fraudscope_app
       
        ports:
            - "8080:8080"
        depends_on:
            mysql:
                condition: service_healthy
        env_file:
            - .env
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/fraudscope
            - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
            - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        networks:
            - fraudscope_network

networks:
    fraudscope_network:
        driver: bridge
volumes:
    mysql_data:
        driver: local