server:
  port: 8080
spring:
  application:
    name: fraudscope
  config:
    import: optional:dotenv:.env
  ai:
    vectorstore:
      azure:
        enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/fraudscope?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  messages:
    basename: currency_type,account_type,transaction_status,transaction_type,approval_status,error_type
    encoding: UTF-8
    fallback-to-system-locale: false
#SMTP  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_FROM}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
# JWT 
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  access:
    token:
      expiration-minutes: 15 
  refresh:
    token:
      expiration-minutes: 1440 # 1 day
      cleanup:
        days: 7

logging:
  level:
    org.springframework.boot.context.config: DEBUG

verification:
  token:
    expiration-minutes: 240 # 4 hour

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui

otp:
  expiration-seconds: 180
  delete-after-days: 30
  max-attempt: 3
