spring:
  application:
    name: fraudscope

  ai:
    vectorstore:
      azure:
        enabled: false

  messages:
    basename: currency_type,account_type,transaction_status,transaction_type,approval_status
    encoding: UTF-8
    fallback-to-system-locale: false
